import os
import google.generativeai as genai
from fastapi import FastAPI, HTTPException
from fastapi.middleware.cors import CORSMiddleware
import json
import random
from dotenv import load_dotenv

load_dotenv()
GEMINI_API_KEY = os.getenv("GEMINI_API_KEY")
genai.configure(api_key=GEMINI_API_KEY)

# --- THE MODEL ROSTER ---
# The system will try these in order. If one fails, it moves to the next.
MODEL_ROSTER = [
  "gemini-2.5-flash",
  "gemini-3-flash-preview",
  "gemini-2.5-flash-lite",
  "gemini-2.0-flash",
  "gemini-2.0-flash-lite",
  "gemini-2.5-pro"
]

app = FastAPI()

app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)

# --- THE DUNGEON MASTER PROMPT ---
def get_ai_narrative(change):
    # 1. Determine the Vibe
    if change < -5:
        vibe = "CATASTROPHIC DISASTER (The Kingdom is falling)"
    elif change < -1:
        vibe = "BAD OMEN (Dark clouds gather)"
    elif change > 5:
        vibe = "GLORIOUS VICTORY (The Golden Age)"
    elif change > 1:
        vibe = "GOOD FORTUNE (Prosperity)"
    else:
        vibe = "UNEASY SILENCE (The wind waits)"

    prompt = f"""
    You are the Dungeon Master of a high-stakes fantasy trading game.
    The market just moved {change}%. The vibe is: {vibe}.
    
    Write a SINGLE sentence describing this event using fantasy metaphors.
    - Do NOT mention percentages or numbers.
    - If negative: Use dragons, plagues, dark magic, crumbling castles, or thieves.
    - If positive: Use harvests, festivals, divine blessings, or royal decrees.
    - If neutral: Use fog, wind, or whispering shadows.
    - Tone: Dark, gritty, medieval.
    
    Output example: "The Dragon of Debt has burned the northern granaries, ash falls on the capital."
    """

    # 2. Roster Fallback System
    for model_name in MODEL_ROSTER:
        try:
            # print(f"🤖 Attempting with {model_name}...") # Uncomment for debug
            model = genai.GenerativeModel(model_name)
            response = model.generate_content(prompt)
            
            # If successful, return the text and the model used
            return response.text.strip(), model_name
            
        except Exception as e:
            print(f"⚠️ {model_name} failed: {e}")
            continue # Try the next model in the list

    # 3. If ALL models fail
    return "The mists of time obscure the future... (AI Connection Failed)", "None"

# --- API ENDPOINTS ---

@app.get("/")
def health_check():
    return {"status": "TradeQuest AI Online", "roster_size": len(MODEL_ROSTER)}

@app.get("/load_level/{level_id}")
def load_level(level_id: str):
    try:
        file_path = os.path.join("data", f"{level_id}.json")
        with open(file_path, "r") as f:
            data = json.load(f)
        return {"level": level_id, "market_data": data}
    except FileNotFoundError:
        raise HTTPException(status_code=404, detail="Level not found")

@app.post("/analyze_turn")
def analyze_turn(change: float):
    # Calls the AI and returns the story + debug info
    story, model_used = get_ai_narrative(change)
    
    # We print the model used to the terminal so you can verify the roster is working
    print(f"🔮 Generated by: {model_used} | Change: {change}%")
    
    return {
        "narrative": story, 
        "model_used": model_used 
    }